TRANSFORMS = {

    "prev_progressive": "log1p",
    "progressive_risk": "log1p",
    "max_similarity": "log1p",
    "std_similarity": "log1p",
    "pattern_risk_ema3": "log1p",
    "origin_drift": "log1p",
    "persistent_drift_count": "log1p",
    "max_toxicity_so_far": "log1p",
    "toxicity_score_ema3": "log1p",
    "mean_risk_so_far": "log1p",
    "interaction_risk_ema3": "log1p",
    "pattern_risk": "log1p",
    "threat_score_ema3": "log1p",
    "interaction_risk": "log1p",
    "toxicity_score": "log1p",
    "threat_score": "log1p",
    "late_risk_increase": "log1p",
    "early_high_risk": "log1p",

    "toxicity_accel": "square",
    "threat_accel": "square",
    "toxicity_diff": "square",
    "threat_diff": "square",
    "risk_slope_3": "square",
    "risk_growth_ratio": "square",

    "drift_acceleration": "binarize",
    "drift_momentum": "binarize",
    "trajectory_linearity": "binarize",
    "angular_coverage": "binarize",
    "mean_similarity": "binarize",
    "topic_drift_score": "binarize",
    "distance_ratio": "binarize",
    "min_similarity": "binarize",
}