TRANSFORMS = {
    "interaction_risk": "log1p",
    "toxicity_score": "log1p",
    "interaction_risk_rolling3_mean": "log1p",
    "threat_score": "log1p",
    "interaction_risk_ema3": "log1p",
    "toxicity_score_rolling3_mean": "log1p",
    "toxicity_score_ema3": "log1p",
    "interaction_risk_rolling3_max": "log1p",
    "toxicity_score_rolling3_max": "log1p",
    "mean_risk_so_far": "log1p",
    "max_toxicity_so_far": "log1p",
    "threat_score_rolling3_max": "log1p",
    "threat_score_ema3": "log1p",
    "threat_score_rolling3_mean": "log1p",
    "max_threat_so_far": "log1p",
    "risk_slope_3": "yeo-johnson",
    "toxicity_diff": "square",
    "toxicity_accel": "square",
    "progressive_risk": "quantile",
    "threat_diff": "square",

    "late_risk_increase": "log1p",
    "early_high_risk": "log1p",
    "state_input_similarity": "yeo-johnson",
    "drift_acceleration": "log1p",
    "long_term_state_similarity": "log1p",
    "prev_progressive": "log1p",
    "long_term_state_drift": "log1p",
    "pattern_risk_rolling3_mean": "log1p",
    "pattern_risk_ema3": "log1p",
    "pattern_risk_rolling3_max": "log1p",
    "state_input_distance": "log1p",

    "state_similarity": "binarize",
    "topic_drift_score": "binarize",
    "pattern_risk": "binarize",
}